---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: MDX Posts
  create: all
  match: src/pages/blog/_posts
  new_doc_ext: ".mdx"
  templates:
  - blog-post
- type: directory
  path: src/pages/blog/_posts/2023
  label: Posts 2023
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: src/pages/blog/_posts
  label: Posts
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
upload_dir: public/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
